/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class swiggy_Validation */

#ifndef _Included_swiggy_Validation
#define _Included_swiggy_Validation
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     swiggy_Validation
 * Method:    password
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_swiggy_Validation_password
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
